.PHONY: build debug flash monitor run clean

build:
	@./build.sh

debug:
	@./debug.sh

flash:
	@./flash.sh

monitor:
	@./monitor.sh

run:
	@./run.sh

clean:
	@echo "Cleaning build artifacts..."
	@make clean
